# Generated by Django 4.1 on 2024-10-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="web_access_record",
            old_name="Web_page_class_date",
            new_name="access_date",
        ),
        migrations.RenameField(
            model_name="web_access_record",
            old_name="Web_Access_Record_name",
            new_name="web_access_record_name",
        ),
    ]
