# Generated by Django 5.1.3 on 2024-12-14 06:38

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_create_date_alter_post_create_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="pubished_date",
            new_name="published_date",
        ),
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 14, 6, 38, 41, 804207, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
